=== Matiixx/TI_Lab/Lab2/zadanie1.dtd
<!ELEMENT indeks (nazwisko, numerAlbumu, przedmioty, przedmioty?, przedmioty?, przedmioty?)>
<!ELEMENT nazwisko (#PCDATA)>
<!ELEMENT numerAlbumu (#PCDATA)>
<!ELEMENT przedmioty (nazwa, (data, ocena), (data, ocena)?)>
<!ELEMENT nazwa (#PCDATA)>
<!ELEMENT data (#PCDATA)>
<!ELEMENT ocena (#PCDATA)>

=== Matiixx/TI_Lab/Lab2/zadanie1.xml
<?xml version="1.0" standalone="no" ?>
<!-- <!DOCTYPE indeks SYSTEM "zadanie1.dtd"> -->
<indeks>
    <nazwisko>Cichostepski</nazwisko>
    <numerAlbumu>123123</numerAlbumu>
    <przedmioty>
        <nazwa>Techniki internetowe</nazwa>
        <data>2022-10-13</data>
        <ocena>5</ocena>
        <data>2022-10-13</data>
        <ocena>5</ocena>
    </przedmioty>

    <przedmioty>
        <nazwa>Techniki internetowe</nazwa>
        <data>2022-10-13</data>
        <ocena>5</ocena>
        <data>2022-10-13</data>
        <ocena>5</ocena>
    </przedmioty>
    
    <przedmioty>
        <nazwa>Techniki internetowe</nazwa>
        <data>2022-10-13</data>
        <ocena>5</ocena>
    </przedmioty>
    <przedmioty>
        <nazwa>Techniki internetowe</nazwa>
        <data>2022-10-13</data>
        <ocena>5</ocena>
        <data>2022-10-13</data>
        <ocena>5</ocena>
    </przedmioty>
</indeks>
